export const FAISALABAD_LOCATIONS = [
  // Towns
  "Lyallpur Town",
  "Madina Town",
  "Jinnah Town",
  "Iqbal Town",
  "Chak Jhumra Town",
  "Jaranwala Town",
  "Samundri Town",
  "Tandlianwala Town",

  // City / Sadar
  "Faisalabad City",
  "Faisalabad Sadar",
  "Chak Jhumra",
  "Jaranwala",
  "Samundri",
  "Tandlianwala",

  // Premium Areas
  "D Ground",
  "People Colony No 1",
  "People Colony No 2",
  "Canal Road",
  "Susan Road",
  "Wapda City",
  "FDA City",
  "Citi Housing",
  "Gulberg",
  "Samanabad",
  "Millat Town",
  "Satiana Road",
  "Jaranwala Road",
  "Samundari Road",
  "Jhang Road",
  "Sargodha Road",
  "Sheikhupura Road",

  // Housing Societies
  "Eden Gardens",
  "Eden Valley",
  "Kohinoor City",
  "Batala Colony",
  "Civil Lines",
  "Officers Colony",
  "Ghulam Muhammad Abad",
  "D-Type Colony",
  "Nishatabad",
  "Gulistan Colony",

  // Villages / Surroundings
  "Manawala",
  "Khurrianwala",
  "Dijkot",
  "Mamu Kanjan",
  "Satiana",
  "Makuana",
  "Sadhar",
  "Garh Fateh Shah",
  "Rodala Road",
  "Lundianwala",
  "Bachiana",
  "Kanjwani",
  "Salatwala",
  "Pansra",
  "Thikriwala",
  "Dhandra",

  // Markets / Bazaars
  "Katchery Bazaar",
  "Chiniot Bazaar",
  "Aminpur Bazaar",
  "Bhawana Bazaar",
  "Jhang Bazaar",
  "Montgomery Bazaar",
  "Karkhana Bazaar",
  "Rail Bazaar",
];