import React, { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { MapContainer, TileLayer, Polygon } from "react-leaflet";
import { colonies } from "./coloniesData";
import { 
  ArrowLeft, 
  ShieldCheck, 
  MapPin, 
  Building, 
  Coins, 
  Grid, 
  Lock, 
  ChevronRight, 
  Info, 
  Phone, 
  User, 
  FileText,
  Clock,
  Sparkles
} from "lucide-react";
import { motion } from "framer-motion";
import confetti from "canvas-confetti";
import { createDeed, getDeeds, generateSignature } from "../../utils/deedService";
import "leaflet/dist/leaflet.css";
import "leaflet-defaulticon-compatibility/dist/leaflet-defaulticon-compatibility.css";
import "leaflet-defaulticon-compatibility";

const PlotDetail = () => {
  const { colonyId, plotId } = useParams();
  const navigate = useNavigate();

  const [colony, setColony] = useState(null);
  const [plot, setPlot] = useState(null);
  
  // Form states
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [offerPrice, setOfferPrice] = useState("");
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  // Deed states (for sold plots)
  const [deedRecord, setDeedRecord] = useState(null);
  const [verificationUrl, setVerificationUrl] = useState("");

  useEffect(() => {
    // 1. Find Colony and Plot from local dataset
    const foundColony = colonies.find((c) => c.id === colonyId);
    if (foundColony) {
      setColony(foundColony);
      const foundPlot = foundColony.plots?.find((p) => p.id === plotId);
      if (foundPlot) {
        setPlot(foundPlot);

        // 2. If plot is sold, ensure it has a registered cryptographic deed
        if (foundPlot.status === "sold") {
          const deeds = getDeeds() || [];
          // Search for existing deed for this plot
          const plotDeedId = `TD-${colonyId}-${plotId}`;
          let existingDeed = deeds.find((d) => d.deedId === plotDeedId);

          if (!existingDeed) {
            // Generate a secure mock deed dynamically so it can be verified on /verify-deed
            existingDeed = createDeed({
              propertyId: plotId,
              title: `${foundPlot.size} Plot - ${foundColony.name} (${foundPlot.block})`,
              location: `${foundPlot.block}, ${foundColony.name}, Faisalabad`,
              price: foundPlot.price === "Sold" ? "PKR 1.2 Crore" : foundPlot.price,
              buyerName: "Zain Ul Abideen",
              buyerEmail: "zain.abideen@gmail.com",
              buyerCNIC: "33100-8877665-3",
              sellerName: "Chaudhary Nisar",
              sellerEmail: "nisar.estate@gmail.com",
              sellerCNIC: "33102-1234321-7",
              registryOffice: "Faisalabad Central Land Registry"
            });
            // Override the autogenerated deedId to make it trace back to this specific plot
            existingDeed.deedId = plotDeedId;
            const updatedDeeds = deeds.filter((d) => d.deedId !== existingDeed.deedId);
            updatedDeeds.push(existingDeed);
            localStorage.setItem("fyp26_trust_deeds", JSON.stringify(updatedDeeds));
          }
          setDeedRecord(existingDeed);

          // Generate public verification link
          const sig = generateSignature(existingDeed.deedId, "public");
          const verifyUrl = `/verify-deed?deedId=${existingDeed.deedId}&role=public&sig=${sig}`;
          setVerificationUrl(verifyUrl);
        }
      }
    }
  }, [colonyId, plotId]);

  if (!colony || !plot) {
    return (
      <div className="min-h-screen bg-slate-950 text-slate-100 flex items-center justify-center">
        <div className="text-center">
          <h2 className="text-xl font-bold text-red-500 mb-2">Plot Not Found</h2>
          <p className="text-slate-400 mb-4">The plot or colony coordinates you are looking for do not exist.</p>
          <button 
            onClick={() => navigate("/map")}
            className="bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-xl text-sm transition"
          >
            Back to Map
          </button>
        </div>
      </div>
    );
  }

  // Calculate plot center for mini-map
  const getPlotCenter = (boundary) => {
    if (!boundary || boundary.length === 0) return colony.center;
    const lats = boundary.map(coord => coord[0]);
    const lngs = boundary.map(coord => coord[1]);
    const centerLat = (Math.min(...lats) + Math.max(...lats)) / 2;
    const centerLng = (Math.min(...lngs) + Math.max(...lngs)) / 2;
    return [centerLat, centerLng];
  };

  const plotCenter = getPlotCenter(plot.boundary);

  // Color mappings
  const getStatusBadgeClass = (status) => {
    switch (status) {
      case "available":
        return "bg-emerald-950/60 text-emerald-400 border border-emerald-800/40";
      case "sold":
        return "bg-red-950/60 text-red-400 border border-red-800/40";
      case "reserved":
        return "bg-amber-950/60 text-amber-400 border border-amber-800/40";
      default:
        return "bg-slate-900 text-slate-400";
    }
  };

  const getStatusText = (status) => {
    switch (status) {
      case "available":
        return "Available for Sale";
      case "sold":
        return "Sold & Blockchain Registered";
      case "reserved":
        return "Under Token / Reserved";
      default:
        return status;
    }
  };

  // Inquiry form submit
  const handleInquirySubmit = (e) => {
    e.preventDefault();
    if (!name || !phone) return;
    
    setSubmitting(true);
    setTimeout(() => {
      setSubmitting(false);
      setIsSubmitted(true);
      
      // Fire confetti
      confetti({
        particleCount: 80,
        spread: 60,
        origin: { y: 0.8 },
        colors: ["#3b82f6", "#6366f1", "#10b981"]
      });
    }, 1200);
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 relative overflow-hidden font-sans pb-16">
      
      {/* Background decorations */}
      <div className="absolute top-0 left-0 w-full h-[500px] bg-gradient-to-b from-blue-900/10 via-transparent to-transparent pointer-events-none" />
      <div className="absolute top-20 right-10 w-[300px] h-[300px] bg-blue-600/5 rounded-full blur-3xl pointer-events-none" />
      
      {/* Main Container */}
      <div className="max-w-6xl mx-auto px-4 pt-6 relative z-10">
        
        {/* Navigation */}
        <button
          onClick={() => navigate("/map")}
          className="flex items-center gap-2 text-slate-400 hover:text-white transition text-xs bg-slate-900/60 hover:bg-slate-900 px-4 py-2 rounded-full border border-slate-800/80 mb-6"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Interactive Map</span>
        </button>

        {/* Hero Details */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-[10px] uppercase font-bold tracking-widest text-blue-400">{colony.name}</span>
              <span className={`text-[10px] font-bold px-2.5 py-0.5 rounded-full ${getStatusBadgeClass(plot.status)}`}>
                {getStatusText(plot.status)}
              </span>
            </div>
            <h1 className="text-3xl font-extrabold tracking-tight text-white flex items-center gap-2">
              {plot.block} — {plot.number}
            </h1>
            <p className="text-sm text-slate-400 mt-1 flex items-center gap-1">
              <MapPin className="w-4 h-4 text-slate-500" /> {plot.block}, {colony.name}, Faisalabad, Punjab
            </p>
          </div>

          <div className="bg-slate-900/40 border border-slate-800/80 rounded-2xl p-4 md:text-right flex flex-col md:items-end min-w-[200px]">
            <span className="text-[10px] text-slate-500 uppercase font-semibold">Estimated Valuation</span>
            <span className="text-2xl font-black text-blue-400 mt-0.5 flex items-center gap-1">
              <Coins className="w-5 h-5 text-yellow-500" /> 
              {plot.status === "sold" && deedRecord ? deedRecord.price : plot.price}
            </span>
          </div>
        </div>

        {/* Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Left Column (Plot overview + Map) */}
          <div className="lg:col-span-2 space-y-6">
            
            {/* Plot specs */}
            <div className="bg-slate-900/30 backdrop-blur-md border border-slate-800/60 rounded-3xl p-6">
              <h2 className="text-base font-bold text-slate-200 mb-4 flex items-center gap-2">
                <Grid className="w-4 h-4 text-blue-400" /> Technical Details
              </h2>
              
              <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-xs">
                <div className="bg-slate-950/50 border border-slate-800/40 p-4 rounded-2xl">
                  <span className="text-slate-500 block mb-0.5">Plot Size</span>
                  <span className="font-semibold text-slate-200 text-sm block">{plot.size}</span>
                </div>
                <div className="bg-slate-950/50 border border-slate-800/40 p-4 rounded-2xl">
                  <span className="text-slate-500 block mb-0.5">Block Name</span>
                  <span className="font-semibold text-slate-200 text-sm block">{plot.block}</span>
                </div>
                <div className="bg-slate-950/50 border border-slate-800/40 p-4 rounded-2xl">
                  <span className="text-slate-500 block mb-0.5">Approval Agency</span>
                  <span className="font-semibold text-emerald-400 text-sm block">{colony.approvalStatus}</span>
                </div>
                <div className="bg-slate-950/50 border border-slate-800/40 p-4 rounded-2xl">
                  <span className="text-slate-500 block mb-0.5">Sector Status</span>
                  <span className="font-semibold text-slate-200 text-sm block">{colony.developmentStatus}</span>
                </div>
                <div className="bg-slate-950/50 border border-slate-800/40 p-4 rounded-2xl">
                  <span className="text-slate-500 block mb-0.5">Electricity / Gas</span>
                  <span className="font-semibold text-slate-200 text-sm block">100% Available</span>
                </div>
                <div className="bg-slate-950/50 border border-slate-800/40 p-4 rounded-2xl">
                  <span className="text-slate-500 block mb-0.5">GIS Lat / Lng</span>
                  <span className="font-mono text-slate-300 text-xs block mt-0.5 truncate" title={`${plotCenter[0].toFixed(5)}, ${plotCenter[1].toFixed(5)}`}>
                    {plotCenter[0].toFixed(4)}°, {plotCenter[1].toFixed(4)}°
                  </span>
                </div>
              </div>
            </div>

            {/* Localized Mini-Map */}
            <div className="bg-slate-900/30 backdrop-blur-md border border-slate-800/60 rounded-3xl overflow-hidden p-3 h-[380px] flex flex-col gap-3">
              <div className="flex items-center justify-between px-3 pt-1">
                <span className="text-xs font-bold text-slate-300 flex items-center gap-1.5">
                  <MapPin className="w-3.5 h-3.5 text-blue-400" /> Geographic GIS Location
                </span>
                <span className="text-[10px] text-slate-500">Vector Plot Outline Mode</span>
              </div>
              
              <div className="flex-1 w-full rounded-2xl overflow-hidden border border-slate-800 z-0">
                <MapContainer
                  center={plotCenter}
                  zoom={17}
                  maxZoom={19}
                  scrollWheelZoom={false}
                  className="w-full h-full"
                >
                  <TileLayer
                    attribution='&copy; <a href="https://carto.com/attributions">CARTO</a>'
                    url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png"
                  />
                  <Polygon
                    positions={plot.boundary}
                    pathOptions={{
                      color: plot.status === "available" ? "#10b981" : plot.status === "sold" ? "#ef4444" : "#f59e0b",
                      fillColor: plot.status === "available" ? "#10b981" : plot.status === "sold" ? "#ef4444" : "#f59e0b",
                      fillOpacity: 0.45,
                      weight: 3
                    }}
                  />
                </MapContainer>
              </div>
            </div>

            {/* Society information */}
            <div className="bg-slate-900/30 backdrop-blur-md border border-slate-800/60 rounded-3xl p-6">
              <h2 className="text-base font-bold text-slate-200 mb-3 flex items-center gap-2">
                <Building className="w-4 h-4 text-indigo-400" /> About {colony.name}
              </h2>
              <p className="text-xs leading-relaxed text-slate-300">
                {colony.description}
              </p>
            </div>

          </div>

          {/* Right Column (Actions / Security Check / Inquiry) */}
          <div className="space-y-6">
            
            {/* Blockchain security check for Sold Plots */}
            {plot.status === "sold" && deedRecord && (
              <div className="bg-gradient-to-br from-slate-900/80 to-blue-950/30 border border-blue-500/20 rounded-3xl p-6 shadow-xl relative overflow-hidden">
                <div className="absolute top-0 right-0 w-24 h-24 bg-blue-500/5 rounded-full blur-2xl pointer-events-none" />
                
                <h3 className="text-xs font-bold text-blue-400 uppercase tracking-widest mb-4 flex items-center gap-1.5">
                  <ShieldCheck className="w-4 h-4 text-emerald-400" /> Blockchain Registry
                </h3>

                <div className="space-y-4">
                  <div className="bg-slate-950/60 border border-slate-800/50 p-4 rounded-2xl">
                    <span className="text-[10px] text-slate-500 uppercase block">Deed ID</span>
                    <span className="font-semibold text-slate-200 text-sm block font-mono mt-0.5">{deedRecord.deedId}</span>
                  </div>

                  <div className="bg-slate-950/60 border border-slate-800/50 p-4 rounded-2xl">
                    <span className="text-[10px] text-slate-500 uppercase block">Registrar Signature</span>
                    <span className="font-semibold text-emerald-400 text-xs block font-mono mt-1 break-all bg-slate-950 p-1.5 rounded-lg border border-slate-900">
                      {deedRecord.blockchainHash.substring(0, 36)}...
                    </span>
                  </div>

                  <div className="bg-slate-950/40 border border-slate-800/40 p-3.5 rounded-2xl flex gap-2">
                    <Lock className="w-5 h-5 text-blue-400 shrink-0 mt-0.5" />
                    <p className="text-[10px] text-slate-400 leading-tight">
                      This property deed is cryptographically signed and stored in the PropSight secure registry ledger.
                    </p>
                  </div>

                  {verificationUrl && (
                    <button
                      onClick={() => navigate(verificationUrl)}
                      className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white font-bold text-xs py-3 rounded-xl transition-all shadow-lg shadow-blue-900/20 flex items-center justify-center gap-1.5 border border-blue-400/20"
                    >
                      Verify Cryptographic Deed <ChevronRight className="w-4 h-4" />
                    </button>
                  )}
                </div>
              </div>
            )}

            {/* Interactive Buy/Token Form for Available/Reserved Plots */}
            {plot.status !== "sold" && (
              <div className="bg-slate-900/30 backdrop-blur-md border border-slate-800/60 rounded-3xl p-6">
                
                {isSubmitted ? (
                  <motion.div 
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    className="text-center py-6"
                  >
                    <div className="w-16 h-16 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 flex items-center justify-center mx-auto mb-4">
                      <Sparkles className="w-8 h-8 animate-bounce" />
                    </div>
                    <h3 className="text-base font-bold text-white mb-2">Inquiry Submitted!</h3>
                    <p className="text-xs text-slate-400 leading-relaxed px-2">
                      A verified PropSight dealer from Faisalabad will reach out to you at <strong>{phone}</strong> within 12 hours.
                    </p>
                    <button 
                      onClick={() => setIsSubmitted(false)}
                      className="mt-6 text-xs text-blue-400 hover:underline"
                    >
                      Submit another request
                    </button>
                  </motion.div>
                ) : (
                  <>
                    <h3 className="text-xs font-bold text-blue-400 uppercase tracking-widest mb-4 flex items-center gap-1.5">
                      <Clock className="w-4 h-4" /> Submit Purchase Offer
                    </h3>
                    
                    <p className="text-[11px] text-slate-400 leading-relaxed mb-4">
                      Submit your contact details and offer price. Authorized dealers will get in touch to coordinate physical site visit.
                    </p>

                    <form onSubmit={handleInquirySubmit} className="space-y-3.5">
                      <div className="flex flex-col gap-1">
                        <label className="text-[10px] text-slate-500 uppercase tracking-wider pl-1">Full Name</label>
                        <div className="relative">
                          <User className="absolute left-3 top-2.5 w-4 h-4 text-slate-600" />
                          <input
                            type="text"
                            required
                            placeholder="Zain Khan"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            className="w-full bg-slate-950 border border-slate-800/80 rounded-xl py-2 pl-9 pr-4 text-xs text-slate-200 placeholder-slate-600 focus:outline-none focus:border-blue-500/60 transition-all"
                          />
                        </div>
                      </div>

                      <div className="flex flex-col gap-1">
                        <label className="text-[10px] text-slate-500 uppercase tracking-wider pl-1">Contact Phone</label>
                        <div className="relative">
                          <Phone className="absolute left-3 top-2.5 w-4 h-4 text-slate-600" />
                          <input
                            type="tel"
                            required
                            placeholder="03001234567"
                            value={phone}
                            onChange={(e) => setPhone(e.target.value)}
                            className="w-full bg-slate-950 border border-slate-800/80 rounded-xl py-2 pl-9 pr-4 text-xs text-slate-200 placeholder-slate-600 focus:outline-none focus:border-blue-500/60 transition-all"
                          />
                        </div>
                      </div>

                      <div className="flex flex-col gap-1">
                        <label className="text-[10px] text-slate-500 uppercase tracking-wider pl-1">Offer Price (PKR)</label>
                        <div className="relative">
                          <Coins className="absolute left-3 top-2.5 w-4 h-4 text-slate-600" />
                          <input
                            type="text"
                            placeholder={`e.g. ${plot.price}`}
                            value={offerPrice}
                            onChange={(e) => setOfferPrice(e.target.value)}
                            className="w-full bg-slate-950 border border-slate-800/80 rounded-xl py-2 pl-9 pr-4 text-xs text-slate-200 placeholder-slate-600 focus:outline-none focus:border-blue-500/60 transition-all"
                          />
                        </div>
                      </div>

                      <button
                        type="submit"
                        disabled={submitting}
                        className="w-full bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs py-3 rounded-xl transition-all shadow-lg shadow-blue-900/10 flex items-center justify-center gap-1"
                      >
                        {submitting ? "Submitting Inquiry..." : "Submit Inquiry Offer"}
                      </button>
                    </form>
                  </>
                )}

              </div>
            )}

            {/* Standard Agent Card */}
            <div className="bg-slate-900/30 backdrop-blur-md border border-slate-800/60 rounded-3xl p-5 flex items-center gap-3">
              <div className="w-10 h-10 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 flex items-center justify-center text-sm font-bold">
                FSD
              </div>
              <div>
                <h4 className="text-xs font-bold text-slate-200">Faisalabad Sales Hub</h4>
                <p className="text-[10px] text-slate-500 mt-0.5">PropSight Authorized Partner</p>
                <p className="text-[10px] text-indigo-400 mt-1 flex items-center gap-1">
                  <Phone className="w-3 h-3" /> +92 (041) 9876543
                </p>
              </div>
            </div>

          </div>

        </div>

      </div>

    </div>
  );
};

export default PlotDetail;
